Quieten output on success
autonomousapps/dependency-analysis-android-gradle-plugin pull request #402
Opened 2021-05-21 23:18 UTC by vlsi

2021-06-01 02:19 UTC, autonomousapps requested changes
Thank you for contributing this! I like the direction, just a few small comments.

2021-06-01 02:19 UTC, autonomousapps commented on gradle/wrapper/gradle-wrapper.properties
> +distributionSha256Sum=7faa7198769f872826c8ef4f1450f839ec27f0b4d5d1e51bade63667cbccd205
Also, I suppose it's worth mentioning that this is orthogonal to the purpose of the PR and should probably be removed and done separately.

2021-06-01 02:19 UTC, autonomousapps commented on src/main/kotlin/com/autonomousapps/tasks/BuildHealthTask.kt
> +      if (consoleText.isNotEmpty()) {
Note to self: run locally, check output.

@vlsi you might want to fix up `ProjectHealthTask` as well.

2021-06-01 04:05 UTC, autonomousapps commented
You should rebase on `main`. I fixed (?) an issue that was causing the gradle daemon to die. Probably running out of memory.

2021-06-01 07:33 UTC, vlsi commented on gradle/wrapper/gradle-wrapper.properties
> +distributionSha256Sum=7faa7198769f872826c8ef4f1450f839ec27f0b4d5d1e51bade63667cbccd205
bin is fine for source navigation for ages: https://github.com/gradle/gradle/blob/master/gradle/wrapper/gradle-wrapper.properties#L3

2021-06-13 16:16 UTC, eugene-krivobokov commented on gradle/wrapper/gradle-wrapper.properties
> +distributionSha256Sum=7faa7198769f872826c8ef4f1450f839ec27f0b4d5d1e51bade63667cbccd205
> bin is fine for source navigation for ages

Does it work as expected? 
We faced with a bug, probably this one: https://youtrack.jetbrains.com/issue/IDEA-231667

2021-06-13 16:37 UTC, vlsi commented on gradle/wrapper/gradle-wrapper.properties
> +distributionSha256Sum=7faa7198769f872826c8ef4f1450f839ec27f0b4d5d1e51bade63667cbccd205
I do not understand what do you mean by "as expected".
I use -bin distributions for a long time, and I have no issues drilling down to Gradle sources

2021-06-13 18:25 UTC, autonomousapps commented
My primary point is I'd prefer to discuss that separately, under another
PR. 

On June 13, 2021, GitHub ***@***.***> wrote:
> @vlsi commented on this pull request.
>

> In gradle/wrapper/gradle-wrapper.properties
> <https://github.com/autonomousapps/dependency-analysis-android-gradle-
> plugin/pull/402#discussion_r650549427>:
>

> @@ -1,5 +1,6 @@ distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists -
distributionUrl=https\://services.gradle.org/distributions/gradle-6.8.3-
all.zip
+distributionSha256Sum=7faa7198769f872826c8ef4f1450f839ec27f0b4d5d1e51bade63667cbccd205

> I do not understand what do you mean by "as expected".
>  I use -bin distributions for a long time, and I have no issues
> drilling down to Gradle sources
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-
plugin/pull/402#discussion_r650549427>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PJ5IGUF54KUM2WLJQTTSTNFZANCNFSM45KADJNQ>.

2021-06-13 18:39 UTC, vlsi commented
@autonomousapps , no problem, I can split two commits in two PRs, however, GitHub does not support [stacked diffs](https://twitter.com/acdlite/status/1255640994239766528), so splitting every commit into individual PR is really really painful.

For instance, no way I would build with `gradle-all.zip`, so I removed `gradle-bin` commit from here, however, now I skip testing at my side.

Don't get me wrong: I know it is a good practice to keep only related changes into a single PR/commit, however, I believe, it would take you a couple of minutes maximum to commit and even rebase the commits. You could cherry-pick the commits and close the PR. There are plenty of options, and all of them are way better than spending time in discussions here.

2021-06-13 19:19 UTC, autonomousapps commented
I know this is tangential, but
> For instance, no way I would build with gradle-all.zip

Why? What makes the all distribution so bad you don't even want it touching your computer?

To the main point, one reason I've been sitting on this is that I thought the CI job failed. In fact, I'm almost certain I told github it was ok to run tests from this, but I just had to do it again 🤷

2021-06-14 04:07 UTC, autonomousapps commented
Thanks for working with me on this, and addressing this long-standing issue.

2021-06-15 05:02 UTC, autonomousapps approved these changes

2021-06-15 05:03 UTC, autonomousapps commented
In principle I approve these changes, but I'd still like to verify behavior locally before merging. Soon (and thanks).

2021-06-15 06:09 UTC, vlsi commented
Thanks, I did try to find a test case (or a way to create such), however I failed, so no tests in PR 🤷‍♂️

2021-06-15 06:18 UTC, autonomousapps commented
I deliberately try to avoid testing against output because it was too
volatile in the beginning. So I just have to see it in action. Thanks
for checking. 

On June 14, 2021, GitHub ***@***.***> wrote:
> Thanks, I did try to find a test case (or a way to create such),
> however I failed, so no tests in PR 🤷‍♂️
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-
plugin/pull/402#issuecomment-861201968>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PJYKAKOLZ4NPC44MB3TS3VAVANCNFSM45KADJNQ>.

2021-06-15 11:23 UTC, eugene-krivobokov commented on gradle/wrapper/gradle-wrapper.properties
> +distributionSha256Sum=7faa7198769f872826c8ef4f1450f839ec27f0b4d5d1e51bade63667cbccd205
Probably, it depends on the project.

2021-06-17 05:26 UTC, autonomousapps requested changes
I noticed an issue with the console output.
```
> Task :buildHealth                                                                                                                                                          
Advice for project :app                                                                                                                                                      
Unused dependencies which should be removed:                                                                                                                                 
  - implementation(project(":entities"))                                                                                                                                     
  - implementation("com.google.dagger:dagger-android-support:2.24")                                                                                                          
  - implementation("androidx.core:core-ktx:1.0.1")                                                                                                                           
  - implementation("androidx.appcompat:appcompat:1.1.0-rc01")                                                                                                                
                                                                                                                                                                             
  Transitively used dependencies that should be declared directly as indicated:
  - implementation("com.google.dagger:dagger:2.24")
  - implementation("javax.inject:javax.inject:1")
                                                                                      
  Dependencies which could be compile-only:                          
  - compileOnly("androidx.annotation:annotation:1.1.0") (was implementation
```
`"Unused dependencies which should be removed:"` should be indented like the other headings.

2021-06-21 10:24 UTC, vlsi commented
```kotlin
        val msg = projectHeaderText(projectAdvice.projectPath) + "\n  " + // <-- added indent here as well
          consoleText.replace("\n", "\n  ")
```

2021-06-21 10:27 UTC, vlsi commented
@autonomousapps , what do you think if `- ` prefix was removed so the output is

```
> Task :buildHealth                                                                                                                                                          
Advice for project :app                                                                                                                                                      
  Unused dependencies which should be removed:                                                                                                                                 
    implementation(project(":entities"))                                                                                                                                     
    implementation("com.google.dagger:dagger-android-support:2.24")                                                                                                          
    implementation("androidx.core:core-ktx:1.0.1")                                                                                                                           
    implementation("androidx.appcompat:appcompat:1.1.0-rc01")                                                                                                                
                                                                                                                                                                             
  Transitively used dependencies that should be declared directly as indicated:
    implementation("com.google.dagger:dagger:2.24")
    implementation("javax.inject:javax.inject:1")
                                                                                      
  Dependencies which could be compile-only:                          
    compileOnly("androidx.annotation:annotation:1.1.0") (was implementation
```

Frankly speaking, it is exactly as readable, however, it would be easier to copy-paste (especially `Transitively used dependencies that should be declared directly`)

2021-06-22 01:12 UTC, autonomousapps commented
Do it, sounds good to me. 

On June 20, 2021, GitHub ***@***.***> wrote:
> @autonomousapps <https://github.com/autonomousapps> , what do you
> think if - prefix was removed so the output would be
>
> > Task :buildHealth Advice for project :app Unused dependencies which
> should be removed: implementation(project(":entities"))
> implementation("com.google.dagger:dagger-android-support:2.24")
> implementation("androidx.core:core-ktx:1.0.1")
> implementation("androidx.appcompat:appcompat:1.1.0-rc01") Transitively
> used dependencies that should be declared directly as indicated:
> implementation("com.google.dagger:dagger:2.24")
> implementation("javax.inject:javax.inject:1") Dependencies which could
> be compile-only: compileOnly("androidx.annotation:annotation:1.1.0")
> (was implementation
> Frankly speaking, it is exactly as readable, however, it would be
> easier to copy-paste (especially Transitively used dependencies that
> should be declared directly)
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-
plugin/pull/402#issuecomment-864921910>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PMJFRSY2Y2TIZQOQATTT4HZVANCNFSM45KADJNQ>.

2021-08-09 06:20 UTC, autonomousapps commented
@vlsi just curious if you still want to work on this. No rush of course.

2021-09-07 06:08 UTC, autonomousapps commented
New PR for same issue: https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/471

2021-09-09 04:09 UTC, autonomousapps commented
Closing in favor of the other PR I just merged.

2021-09-09 04:09 UTC, closed without merging