Sort the output of ProjectHealthConsoleReportBuilder
autonomousapps/dependency-analysis-android-gradle-plugin pull request #554
Opened 2022-01-13 09:59 UTC by mvegter

2022-01-14 07:17 UTC, mvegter commented on src/main/kotlin/com/autonomousapps/internal/advice/ProjectHealthConsoleReportBuilder.kt
> +        }.joinToString(prefix = "  ", separator = "\n  ")
This is actually the same formatting as is used by the v1 AdvicePrinter. On our internal projects (against latest main with v2 model) the output is unsorted, hence the change.

2022-01-14 20:08 UTC, autonomousapps commented on src/main/kotlin/com/autonomousapps/internal/advice/ProjectHealthConsoleReportBuilder.kt
> +        }.joinToString(prefix = "  ", separator = "\n  ")
Is it important for you that there be two spaces prefixing each line? Trying to understand if this is an implicit API.

2022-01-15 08:03 UTC, mvegter commented on src/main/kotlin/com/autonomousapps/internal/advice/ProjectHealthConsoleReportBuilder.kt
> +        }.joinToString(prefix = "  ", separator = "\n  ")
We do not depend on the indent behavior. Personally, I like the two spaces indent as it easier to read and consistent with the v1 version.

2022-01-16 19:35 UTC, autonomousapps requested changes
I think I realized why I'm confused. At the top of this init block, there's this:
```kotlin
val dependencyAdvice = projectAdvice.dependencyAdvice
val removeAdvice = mutableSetOf<Advice>()
val addAdvice = mutableSetOf<Advice>()
val changeAdvice = mutableSetOf<Advice>()
val compileOnlyAdvice = mutableSetOf<Advice>()
val processorAdvice = mutableSetOf<Advice>()
```
I'm almost certain that `val dependencyAdvice = projectAdvice.dependencyAdvice` _is_ sorted. However, I break up that large sorted set into a handful of _hash_ sets, which lose the ordering information. If each of those mutable sets were instead `sortedSetOf<Advice>()`, then I think you could drop the `mapToOrderedSet`, which I would prefer. Would you mind testing that?

I don't mind you changing it back to the double-spaced output.

2022-01-16 20:43 UTC, autonomousapps approved these changes
Thanks! LGTM.

2022-01-16 21:55 UTC, merged

2022-01-19 07:09 UTC, mvegter commented
@autonomousapps  There is a small regression here, we are sorting on the artifact and not on the suggestion, I guess that is why the initial one was using `mapToOrderSet` instead of the sortedSet

2022-01-19 07:22 UTC, autonomousapps commented
Sounds like we need a regression test!

2022-01-19 07:22 UTC, autonomousapps commented
I was going to reopen this, but it's a PR and not an issue. Mind filing an issue? I think this situation is amenable to a simpler unit test of this particular class.