Use buffered writer when writing ExplodedJar to file
autonomousapps/dependency-analysis-android-gradle-plugin pull request #824
Opened 2022-11-23 21:16 UTC by daanschipper

Fixes #823

2022-11-23 21:19 UTC, daanschipper commented
Disclaimer: I've not used moshi before, open for suggestions on some improvement. I'm not sure about the pretty output, I'd was looking for something along the lines of `getJsonSetAdapter<ExplodedJar>().toPrettyJson()` but couldn't find it.

2022-11-26 01:06 UTC, autonomousapps approved these changes
Thank you, I really appreciate this! Will merge once green on CI.

2022-11-26 23:42 UTC, autonomousapps commented
There are an awful lot of test failures, and unfortunately that means the build scan is too large to be viewed.

2022-11-28 21:15 UTC, autonomousapps requested changes
Thanks for the fix. Left some comments.

2022-11-28 21:15 UTC, autonomousapps commented on src/main/kotlin/com/autonomousapps/internal/utils/moshi.kt
> + * By default the output is compacted.
> Buffers writes of the set to disk, using the indent to make the output human-readable. By default, the output is compacted.

use that for both new methods :)

2022-11-28 21:15 UTC, autonomousapps commented on src/functionalTest/groovy/com/autonomousapps/jvm/ExplodeJarSpec.groovy
> +final class ExplodeJarSpec extends AbstractJvmSpec {
I'm a little worried about the fragility of this test. Any change to the relevant models will break the test, but that, to me, is just noise—not useful information.

I think you should just delete this spec, the `ExplodeJarProject`, and the two new resources files as well. I don't think they add anything useful when compared to the maintenance cost.

2022-11-28 21:34 UTC, daanschipper commented on src/main/kotlin/com/autonomousapps/internal/utils/moshi.kt
> +}
Was not aware of `.use { }`, that looks cleaner indeed!

2022-11-29 19:53 UTC, autonomousapps approved these changes
Thanks!

2022-11-29 19:53 UTC, merged